customhost = "employee.cmqt4stzzdnf.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "ericwongtungsian-bucket"
customregion = "us-east-1"
